"""initial schema

Revision ID: cf412b14d6e8
Revises: 
Create Date: 2026-01-26 23:52:37.935320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf412b14d6e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertorios', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_repertorios_id'), 'repertorios', ['id'], unique=False)
    op.drop_constraint(op.f('repertorios_owner_id_fkey'), 'repertorios', type_='foreignkey')
    op.create_foreign_key(None, 'repertorios', 'users', ['user_id'], ['id'])
    op.drop_column('repertorios', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertorios', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'repertorios', type_='foreignkey')
    op.create_foreign_key(op.f('repertorios_owner_id_fkey'), 'repertorios', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_repertorios_id'), table_name='repertorios')
    op.drop_column('repertorios', 'user_id')
    # ### end Alembic commands ###
